// Contenido de Encontrándonos. Todo en español neutro.
window.DATA = {

  // ───────────────────────── CARTAS ─────────────────────────
  cartas: {
    nosotros: {
      name: 'Nosotros', icon: '❤️', blurb: 'Lo que hemos vivido y lo que somos juntos',
      cards: [
        '¿Cuál fue tu primera impresión de mí? Sin suavizarla.',
        '¿Qué momento conmigo recuerdas con más cariño?',
        '¿Qué pequeña cosa que hago te gusta más de lo que admites?',
        '¿Qué crees que hacemos especialmente bien como pareja?',
        '¿En qué momento supiste que esto iba en serio?',
        '¿Qué costumbre mía se te ha pegado sin que te dieras cuenta?',
        '¿Cuál ha sido nuestra conversación más larga y de qué iba?',
        'Si nuestra relación fuera una película, ¿de qué género sería y quién la protagonizaría?',
        '¿Qué canción te hace pensar en mí aunque no tenga nada que ver?',
        '¿Qué te gustaría que hiciéramos más seguido?',
        '¿Qué foto nuestra elegirías para enmarcar?',
        '¿Qué es lo primero que quieres hacer la próxima vez que nos veamos?'
      ]
    },
    absurdas: {
      name: 'Absurdas', icon: '😂', blurb: 'Preguntas que no sirven para nada',
      cards: [
        'Si mañana despertáramos convertidos en animales, ¿qué animal serías tú y cuál sería yo?',
        '¿Qué objeto absurdo llevarías a una isla desierta?',
        'Si tuvieras que describirme usando solamente tres comidas, ¿cuáles elegirías?',
        'Si fuéramos un dúo de villanos, ¿cuál sería nuestro plan malvado más inútil?',
        '¿Qué electrodoméstico de tu casa crees que te juzga en silencio?',
        'Si tuvieras que pelear contra cien patos del tamaño de un gato o un gato del tamaño de cien patos, ¿qué eliges?',
        '¿Qué nombre le pondrías a nuestro restaurante y cuál sería el plato estrella?',
        'Si fueras una fruta, ¿cuál serías y por qué nadie te compraría?',
        '¿Cuál sería tu música de entrada si fueras luchador profesional?',
        'Si pudieras prohibir una palabra para siempre, ¿cuál sería?',
        '¿Qué superpoder completamente inútil te gustaría tener?',
        'Si te convirtieras en un mueble de mi casa, ¿cuál serías?'
      ]
    },
    profundas: {
      name: 'Profundas', icon: '🧠', blurb: 'Para hablar despacio',
      cards: [
        '¿Qué parte de tu personalidad crees que pocas personas llegan a conocer?',
        '¿Qué cosa de tu futuro te ilusiona realmente?',
        '¿Qué necesitas sentir para saber que estás en un lugar seguro con alguien?',
        '¿Qué opinión has cambiado por completo en los últimos años?',
        '¿Qué le dirías a tu yo de quince años si tuvieras un minuto?',
        '¿Qué te hace sentir en casa, aunque estés lejos?',
        '¿Qué es algo que te costó mucho aprender sobre ti?',
        '¿A quién admiras en silencio y por qué?',
        '¿Qué te gustaría que la gente recordara de ti?',
        '¿Qué haces cuando nadie te ve que dice mucho de quién eres?'
      ]
    },
    coquetas: {
      name: 'Coquetas', icon: '🔥', blurb: 'Un poco de temperatura',
      cards: [
        '¿Qué cosa mía te parece especialmente atractiva?',
        '¿Cuál sería nuestra cita perfecta si tuviéramos una noche completamente libre?',
        '¿Qué momento conmigo te puso especialmente nervioso o nerviosa?',
        '¿Qué ropa mía te gusta más? ¿Y cuál esconderías?',
        '¿Qué es lo que más te gusta de mi voz?',
        'Describe en una frase cómo te gustaría que te saludara la próxima vez que nos veamos.',
        '¿Qué te dice mi mirada cuando no digo nada?',
        '¿Cuál ha sido el beso que más recuerdas?',
        '¿Qué parte de una cita es tu favorita: la espera, el durante o el después?',
        '¿Qué cumplido mío te ha durado más tiempo en la cabeza?'
      ]
    },
    retos: {
      name: 'Retos', icon: '🎯', blurb: 'Hay que hacerlo, no contarlo',
      type: 'reto',
      cards: [
        'Haz una imitación de tu pareja durante 20 segundos.',
        'Describe a tu pareja como si fueras un crítico gastronómico.',
        'Canta el estribillo de una canción que elegiría tu pareja.',
        'Haz una declaración dramática de amor usando tres palabras que el otro elija.',
        'Presenta a tu pareja como si fuera la estrella de un programa de televisión.',
        'Narra lo que está haciendo tu pareja como un documental de animales durante 20 segundos.',
        'Haz tu mejor cara de "te estoy escuchando" mientras el otro habla de algo aburrido.',
        'Vende el objeto más cercano que tengas como si fuera un artículo de lujo.',
        'Recita un poema improvisado de cuatro versos sobre lo que estás bebiendo.',
        'Habla durante 30 segundos sin usar la letra "e".'
      ]
    },
    adiviname: {
      name: 'Adivíname', icon: '🔮', blurb: 'Elijan en secreto y revelen a la vez',
      type: 'adivina',
      cards: [
        { q: '¿Qué elegiría: una semana en la playa o una semana en la montaña?', a: ['Playa', 'Montaña'] },
        { q: 'Viernes por la noche: ¿salir o quedarse en casa?', a: ['Salir', 'Quedarse'] },
        { q: '¿Desayuno dulce o salado?', a: ['Dulce', 'Salado'] },
        { q: '¿Qué prefiere perder: el teléfono o la billetera?', a: ['Teléfono', 'Billetera'] },
        { q: '¿Película de terror o comedia romántica?', a: ['Terror', 'Comedia romántica'] },
        { q: '¿Viajar con mochila o con maleta grande?', a: ['Mochila', 'Maleta'] },
        { q: '¿Llegar siempre temprano o justo a tiempo?', a: ['Temprano', 'Justo a tiempo'] },
        { q: '¿Perros o gatos?', a: ['Perros', 'Gatos'] },
        { q: '¿Cocinar juntos o pedir comida?', a: ['Cocinar', 'Pedir'] },
        { q: '¿Saber el futuro o poder cambiar el pasado?', a: ['El futuro', 'El pasado'] },
        { q: '¿Invierno o verano?', a: ['Invierno', 'Verano'] },
        { q: '¿Una cena elegante o una pizza en el sillón?', a: ['Cena elegante', 'Pizza'] }
      ]
    },
    imagina: {
      name: 'Imagina que…', icon: '💭', blurb: 'Escenarios para soñar un rato',
      cards: [
        'Tenemos 10 millones de dólares y debemos gastarlos juntos en 24 horas. ¿Qué hacemos?',
        'Podemos aparecer instantáneamente en cualquier lugar del mundo. ¿Dónde aparecemos?',
        'Tenemos que vivir un año en otro país. ¿Cuál elegimos?',
        'Abrimos un pequeño negocio juntos. ¿De qué es y quién hace qué?',
        'Nos quedamos encerrados una noche en un museo. ¿Cuál y qué hacemos?',
        'Ganamos un viaje en tren de una semana. ¿Por dónde pasa?',
        'Mañana nos levantamos siendo famosos. ¿Por qué?',
        'Podemos revivir un día que ya pasamos juntos. ¿Cuál?',
        'Tenemos una casa de fin de semana. ¿Dónde está y cómo es?',
        'Podemos invitar a cenar a tres personas, vivas o no. ¿A quiénes?'
      ]
    },
    duelo: {
      name: 'Duelo', icon: '🏆', blurb: 'Siempre hay un ganador',
      type: 'duelo',
      cards: [
        'Cada uno tiene 30 segundos para explicar por qué debería elegir la próxima película.',
        'Quien diga más países de Sudamérica en 20 segundos gana.',
        'Hagan su mejor acento extranjero. El otro elige al ganador… con honestidad.',
        'Gana quien mantenga la cara seria más tiempo mientras el otro intenta hacerle reír.',
        'Cada uno nombra animales que empiecen con "P". Pierde el primero que se quede en blanco.',
        'Gana el mejor piropo improvisado en 10 segundos.',
        'Quien cuente la anécdota más vergonzosa en un minuto gana.',
        'Cada uno defiende su comida favorita como si fuera abogado. Gana el mejor alegato.',
        'Gana quien recuerde más detalles de nuestra primera cita.',
        'Piedra, papel o tijera a cámara. Al mejor de tres.',
        'Gana quien imite mejor a un presentador de noticias anunciando lo que cenó hoy.'
      ]
    }
  },

  // ───────────────── ¿QUIÉN DE LOS DOS? ─────────────────
  quien: [
    '¿Quién de los dos sobreviviría mejor en una isla desierta?',
    '¿Quién se ríe primero en una discusión?',
    '¿Quién es más probable que se pierda con el GPS encendido?',
    '¿Quién dice "solo un capítulo más" y ve cuatro?',
    '¿Quién se enamoró primero?',
    '¿Quién es más celoso o celosa?',
    '¿Quién cocina mejor?',
    '¿Quién gasta más en cosas que no necesita?',
    '¿Quién llora con más facilidad en las películas?',
    '¿Quién pediría perdón primero?',
    '¿Quién sería mejor en un concurso de baile?',
    '¿Quién tarda más en arreglarse?',
    '¿Quién es más probable que hable con desconocidos en un viaje?',
    '¿Quién guarda mejor un secreto?',
    '¿Quién ganaría en una pelea de almohadas?',
    '¿Quién es más romántico o romántica?',
    '¿Quién se duerme primero viendo una película?',
    '¿Quién es más desordenado o desordenada?',
    '¿Quién recuerda mejor las fechas importantes?',
    '¿Quién sería el primero en ser eliminado de un reality?',
    '¿Quién es más probable que adopte un animal sin consultar?',
    '¿Quién manda los mensajes más largos?',
    '¿Quién tiene más paciencia?',
    '¿Quién es más competitivo o competitiva?',
    '¿Quién haría el ridículo en una boda con más gusto?',
    '¿Quién se come el último trozo de pizza sin preguntar?',
    '¿Quién planea mejor los viajes?',
    '¿Quién ronca? Sean honestos.',
    '¿Quién tiene mejor gusto musical?',
    '¿Quién da los mejores abrazos?',
    '¿Quién sobreviviría más tiempo sin internet?',
    '¿Quién sería mejor espía?',
    '¿Quién se pone de peor humor con hambre?',
    '¿Quién es más probable que se haga famoso por accidente?',
    '¿Quién es más coqueto o coqueta?',
    '¿Quién dice "te quiero" más veces al día?',
    '¿Quién sería el primero en rendirse en una caminata larga?',
    '¿Quién tiene la risa más contagiosa?',
    '¿Quién se pone más nervioso al conocer a la familia del otro?',
    '¿Quién ganaría en un concurso de preguntas de cultura general?',
    '¿Quién es más probable que se olvide algo importante en un viaje?',
    '¿Quién besa mejor? Respuesta diplomática no vale.',
    '¿Quién sería mejor presidente o presidenta del mundo?',
    '¿Quién se pondría a llorar primero en una despedida en el aeropuerto?'
  ],

  // ───────────────── PREGUNTAS PROFUNDAS ─────────────────
  profundas: [
    '¿Qué recuerdo de tu infancia te sigue pareciendo mágico?',
    '¿Qué es algo que antes te daba miedo y ya no?',
    '¿Qué día de tu vida volverías a vivir tal cual fue?',
    '¿Qué te gustaría aprender si tuvieras un año entero libre?',
    '¿Qué lugar te cambió un poco por dentro?',
    '¿Qué consejo recibiste que sigues usando?',
    '¿En qué te pareces a tu mamá o a tu papá, aunque te cueste admitirlo?',
    '¿Qué cosa sencilla te hace feliz de verdad?',
    '¿Qué te gustaría que entendiera mejor de ti?',
    '¿Qué decisión tomaste que, mirando atrás, fue más valiente de lo que pensabas?',
    '¿Cómo te imaginas un domingo perfecto dentro de diez años?',
    '¿Qué te hace sentir orgullo de ti, aunque no lo digas?',
    '¿Qué amistad te marcó más y por qué?',
    '¿Qué tradición te gustaría que tuviéramos?',
    '¿Qué es lo que más extrañas de un lugar donde viviste?',
    '¿Qué pregunta te gustaría que alguien te hiciera más seguido?',
    '¿Qué te enseñó tu peor trabajo?',
    '¿Cómo sabes que alguien te quiere, más allá de las palabras?',
    '¿Qué sueño tenías de niño o niña que todavía te hace sonreír?',
    '¿Qué libro, película o canción llegó en el momento justo de tu vida?',
    '¿Qué te gustaría hacer antes de cumplir el próximo año?',
    '¿Qué parte de tu rutina protegerías a toda costa?',
    '¿Qué te calma cuando todo se complica?',
    '¿Qué te gustaría que hiciéramos distinto la próxima vez que discutamos?',
    '¿Cuál es la mejor sorpresa que te han dado?',
    '¿Qué valor tuyo no negociarías nunca?',
    '¿Qué te gustaría contarle a alguien que ya no está?',
    '¿Cómo era tu cuarto cuando tenías doce años?',
    '¿Qué olor te transporta directo a otra época?',
    '¿Qué crees que aprendimos el uno del otro?'
  ],

  // ───────────────── SIN FILTRO ─────────────────
  sinfiltro: {
    1: { name: 'Suave', chili: '🌶️', cards: [
      '¿Qué fue lo primero que te llamó la atención de mí físicamente?',
      '¿Cuál es tu recuerdo favorito de una mañana juntos?',
      '¿Qué perfume o aroma mío reconocerías con los ojos cerrados?',
      '¿Qué te pondrías para impresionarme en una cita?',
      '¿Qué gesto mío te desarma?',
      '¿Cuándo fue la última vez que pensaste en mí en un momento inoportuno?',
      '¿Qué tipo de beso prefieres: lento, sorpresa o de despedida?',
      '¿Qué parte de nuestras videollamadas es tu favorita?',
      '¿Qué canción pondrías para una noche lenta conmigo?',
      '¿Qué foto mía guardas como favorita?',
      'Dime algo que te encantaría escuchar de mí más seguido.',
      '¿En qué lugar público te habría encantado besarme?'
    ]},
    2: { name: 'Atrevido', chili: '🌶️🌶️', cards: [
      '¿Qué es lo que más te provoca de mí cuando estoy cerca?',
      'Describe nuestra próxima cita ideal… desde que se cierra la puerta.',
      '¿Qué te gustaría que te susurrara al oído?',
      '¿Cuál es tu fantasía de viaje romántico conmigo?',
      '¿Qué te pone más: que te miren, que te hablen o que te toquen?',
      '¿Qué prenda mía te gustaría quitarme primero?',
      '¿Cuál ha sido el momento más atrevido que hemos vivido?',
      '¿Qué parte de mi cuerpo besarías primero al vernos?',
      '¿Qué mensaje mío te ha subido la temperatura?',
      '¿Qué cosa te da vergüenza pedir pero te encantaría?',
      '¿Lugar más inesperado donde te gustaría besarme?',
      'Cuéntame un sueño conmigo que no me hayas contado.'
    ]},
    3: { name: 'Sin filtro', chili: '🌶️🌶️🌶️', cards: [
      '¿Qué es lo primero que harías si pudiéramos estar juntos esta noche?',
      'Describe con tres palabras cómo te gusta que te toquen.',
      '¿Qué fantasía tienes conmigo que todavía no me has contado?',
      '¿Qué recuerdo nuestro en la intimidad repites en tu cabeza?',
      '¿Qué te gustaría probar la próxima vez que nos veamos?',
      '¿Dónde te gustaría que pasara nuestra noche más memorable?',
      '¿Qué es lo más atractivo que he hecho sin darme cuenta?',
      'Pon una regla para nuestro próximo reencuentro.',
      '¿Luz encendida o apagada? Defiende tu respuesta.',
      '¿Qué te gustaría que me pusiera la próxima vez que nos veamos?',
      'Dime algo que te encante y que nunca te haya dicho que me encanta.',
      '¿Qué es lo que más extrañas de mí cuando apagamos la cámara?'
    ]}
  },

  // ───────────────── RETOS ─────────────────
  retos: [
    'Haz una imitación de tu pareja.',
    'Canta 15 segundos de una canción elegida por el otro.',
    'Describe a tu pareja usando solamente tres adjetivos.',
    'Haz un brindis completamente exagerado.',
    'Cuenta una vergüenza que todavía no le hayas contado.',
    'Durante la próxima ronda tienes que hablar con acento.',
    'Baila 10 segundos la canción que el otro tararee.',
    'Muestra a cámara lo último que compraste y véndelo como algo imprescindible.',
    'Imita cómo te despiertas un lunes.',
    'Dile a tu pareja un cumplido exageradamente específico.',
    'Haz una pose de modelo de revista y mantenla 10 segundos.',
    'Lee en voz alta el último mensaje que le mandaste a tu mamá.',
    'Hasta la próxima ronda, termina cada frase con "mi amor".',
    'Haz un comercial de 20 segundos sobre tu pareja.',
    'Cuenta un chiste malo con total seriedad.',
    'Dibuja a tu pareja en 30 segundos y muéstralo a cámara.',
    'Imita a tu pareja cuando tiene hambre.',
    'Habla como narrador de fútbol mientras tomas un sorbo de tu bebida.',
    'Haz una reverencia dramática y agradece al público por esta relación.',
    'Muestra a cámara la cosa más rara que tengas en la habitación y cuenta su historia.',
    'Recita el abecedario hacia atrás desde la "J".',
    'Explica tu trabajo como si tuvieras cinco años.',
    'Haz tu mejor sonido de animal y que el otro adivine cuál es.',
    'Mira a cámara y declama un piropo como en una telenovela.',
    'Escribe a mano una nota para tu pareja y léela en voz alta.',
    'Durante un minuto, solo puedes responder con preguntas.',
    'Imita a un personaje famoso hasta que el otro lo adivine.',
    'Cuenta cómo nos conocimos como si fuera un cuento de hadas.',
    'Haz 10 sentadillas mientras dices cosas que te gustan del otro.',
    'Pon la canción que el otro elija y haz playback.'
  ],

  // ───────────────── PENITENCIAS ─────────────────
  penitencias: [
    'Haz una imitación de quien quiera tu pareja.',
    'Manda un audio cantando, aunque sea a cámara.',
    'Responde una pregunta extra que elija el otro.',
    'Haz un cumplido exageradamente específico.',
    'Cuenta una vergüenza.',
    'Baila durante 10 segundos.',
    'Deja que el otro elija la próxima canción.',
    'Habla con voz de locutor hasta la próxima ronda.',
    'Muéstrale a cámara la última foto de tu galería.',
    'Di tres cosas que te gustan del otro sin repetir ninguna dicha antes.'
  ],


  // ───────────────── PROST (penitencias con bebida, a distancia) ─────────────────
  prost: [
    'Brinda a cámara y dile a {o} algo que pensaste y nunca le dijiste.',
    'Un trago mirando a {o} a los ojos por la cámara, sin reírte.',
    'Brinda por la próxima vez que se vean y di la fecha que te gustaría.',
    'Un trago y dile a {o} qué es lo que más extrañas.',
    'Brinda en alemán y en español: ¡Prost! ¡Salud! Y un trago.',
    'Un trago y cuéntale a {o} qué harías ahora si estuviera ahí.',
    'Brinda por algo que {o} hizo esta semana y que te gustó.'
  ],
  // ───────────────── DIBUJA Y ADIVINA ─────────────────
  dibujo: {
    animales: { name: 'Animales', words: ['Jirafa', 'Pulpo', 'Pingüino', 'Caracol', 'Murciélago', 'Llama', 'Tiburón', 'Camaleón', 'Perezoso', 'Flamenco', 'Erizo', 'Canguro', 'Búho', 'Medusa'] },
    peliculas: { name: 'Películas', words: ['Titanic', 'El Rey León', 'Jurassic Park', 'Harry Potter', 'Star Wars', 'Toy Story', 'Shrek', 'Tiburón', 'Avatar', 'Buscando a Nemo', 'Matrix', 'Frozen', 'King Kong', 'Up'] },
    personajes: { name: 'Personajes', words: ['Batman', 'Sirenita', 'Drácula', 'Papá Noel', 'Pirata', 'Astronauta', 'Bruja', 'Mago', 'Superman', 'Momia', 'Vaquero', 'Ninja', 'Robot', 'Fantasma'] },
    objetos: { name: 'Objetos', words: ['Paraguas', 'Tijeras', 'Bicicleta', 'Lámpara', 'Reloj de arena', 'Tetera', 'Escalera', 'Guitarra', 'Candado', 'Mochila', 'Telescopio', 'Ancla', 'Brújula', 'Microondas'] },
    comida: { name: 'Comida', words: ['Empanada', 'Sushi', 'Pizza', 'Helado', 'Taco', 'Hamburguesa', 'Arepa', 'Huevo frito', 'Palomitas', 'Croissant', 'Asado', 'Sandía', 'Fondue', 'Alfajor'] },
    absurdas: { name: 'Situaciones absurdas', words: ['Un perro manejando', 'Un pez en bicicleta', 'Una vaca en la Luna', 'Un gato abogado', 'Un tiburón en la ducha', 'Una nube enojada', 'Un dinosaurio en la oficina', 'Una pizza volando', 'Un pingüino de vacaciones', 'Un fantasma con resfriado', 'Una jirafa en ascensor', 'Un caracol con prisa'] },
    pareja: { name: 'Cosas de pareja', words: ['Primera cita', 'Videollamada', 'Beso', 'Abrazo', 'Anillo', 'Cena romántica', 'Aeropuerto', 'Carta de amor', 'Pelea por la manta', 'Serenata', 'Luna de miel', 'Ramo de flores', 'Despedida', 'Reencuentro'] }
  },

  // ───────────────── MÍMICA ─────────────────
  mimica: [
    'Cocinar panqueques', 'Pescar', 'Cambiar un pañal', 'Hacer surf', 'Lavarse los dientes', 'Pasear un perro rebelde',
    'Ir en montaña rusa', 'Tocar la batería', 'Ver una película de terror', 'Perder el bus', 'Subir una montaña', 'Despertarse tarde',
    'Hacer yoga', 'Pisar un Lego', 'Ganar un Óscar', 'Pelar una cebolla', 'Comer espaguetis', 'Desfilar en pasarela',
    'Bañar a un gato', 'Jugar al tenis', 'Bucear', 'Ser un robot', 'Pintar una pared', 'Abrir un frasco imposible',
    'Esquiar', 'Ser una gallina', 'Conducir bajo la lluvia', 'Tomarse una selfie', 'Bailar tango', 'Hacer malabares',
    'Patinar sobre hielo', 'Ordeñar una vaca', 'Recibir una mala noticia', 'Buscar las llaves', 'Ser una estatua', 'Montar a caballo',
    'Planchar una camisa', 'Llegar tarde a una boda', 'Cantar ópera', 'Atrapar una mosca'
  ],

  // ───────────────── PALABRA PROHIBIDA ─────────────────
  tabu: [
    { w: 'Playa', x: ['Arena', 'Mar', 'Sol', 'Verano', 'Olas'] },
    { w: 'Café', x: ['Taza', 'Mañana', 'Negro', 'Leche', 'Despertar'] },
    { w: 'Cumpleaños', x: ['Torta', 'Velas', 'Fiesta', 'Regalo', 'Años'] },
    { w: 'Avión', x: ['Volar', 'Aeropuerto', 'Piloto', 'Viaje', 'Alas'] },
    { w: 'Guitarra', x: ['Cuerdas', 'Música', 'Tocar', 'Instrumento', 'Rock'] },
    { w: 'Pizza', x: ['Queso', 'Italia', 'Masa', 'Horno', 'Porción'] },
    { w: 'Volcán', x: ['Lava', 'Erupción', 'Montaña', 'Fuego', 'Ceniza'] },
    { w: 'Dentista', x: ['Dientes', 'Muela', 'Doctor', 'Boca', 'Dolor'] },
    { w: 'Nieve', x: ['Frío', 'Blanco', 'Invierno', 'Copo', 'Esquiar'] },
    { w: 'Beso', x: ['Labios', 'Boca', 'Amor', 'Pareja', 'Mejilla'] },
    { w: 'Telenovela', x: ['Televisión', 'Drama', 'Capítulo', 'Actor', 'Amor'] },
    { w: 'Paraguas', x: ['Lluvia', 'Mojar', 'Abrir', 'Agua', 'Tormenta'] },
    { w: 'Vino', x: ['Uva', 'Copa', 'Tinto', 'Botella', 'Blanco'] },
    { w: 'Gimnasio', x: ['Pesas', 'Ejercicio', 'Músculo', 'Entrenar', 'Correr'] },
    { w: 'Luna', x: ['Noche', 'Llena', 'Cielo', 'Astronauta', 'Satélite'] },
    { w: 'Perfume', x: ['Oler', 'Aroma', 'Frasco', 'Olor', 'Rociar'] },
    { w: 'Mate', x: ['Yerba', 'Bombilla', 'Argentina', 'Termo', 'Agua'] },
    { w: 'Pasaporte', x: ['Viajar', 'Documento', 'Aeropuerto', 'País', 'Sello'] },
    { w: 'Fantasma', x: ['Miedo', 'Muerto', 'Sábana', 'Casa', 'Asustar'] },
    { w: 'Hamaca', x: ['Colgar', 'Descansar', 'Árbol', 'Mecer', 'Siesta'] },
    { w: 'Chocolate', x: ['Cacao', 'Dulce', 'Marrón', 'Tableta', 'Bombón'] },
    { w: 'Despertador', x: ['Alarma', 'Mañana', 'Sonar', 'Dormir', 'Reloj'] },
    { w: 'Selfie', x: ['Foto', 'Teléfono', 'Cámara', 'Cara', 'Redes'] },
    { w: 'Abuela', x: ['Mamá', 'Familia', 'Nieto', 'Vieja', 'Cocinar'] },
    { w: 'Dinosaurio', x: ['Extinto', 'Jurásico', 'Fósil', 'Reptil', 'Grande'] },
    { w: 'Montaña rusa', x: ['Parque', 'Vértigo', 'Subir', 'Bajar', 'Gritar'] },
    { w: 'Sirena', x: ['Mar', 'Cola', 'Pez', 'Mujer', 'Cantar'] },
    { w: 'Tatuaje', x: ['Piel', 'Tinta', 'Aguja', 'Dibujo', 'Brazo'] },
    { w: 'Volante', x: ['Auto', 'Manejar', 'Girar', 'Conducir', 'Rueda'] },
    { w: 'Brindis', x: ['Copa', 'Salud', 'Chocar', 'Celebrar', 'Beber'] },
    { w: 'Domingo', x: ['Semana', 'Día', 'Descanso', 'Lunes', 'Sábado'] },
    { w: 'Terremoto', x: ['Temblor', 'Tierra', 'Sismo', 'Mover', 'Placa'] },
    { w: 'Almohada', x: ['Cama', 'Dormir', 'Cabeza', 'Suave', 'Funda'] },
    { w: 'Payaso', x: ['Circo', 'Nariz', 'Roja', 'Reír', 'Maquillaje'] },
    { w: 'Maleta', x: ['Viaje', 'Ropa', 'Equipaje', 'Ruedas', 'Empacar'] }
  ],

  // ───────────────── ¿QUÉ PREFIERES? ─────────────────
  prefieres: [
    ['Poder volar', 'Ser invisible'],
    ['Vivir en la playa', 'Vivir en la montaña'],
    ['Nunca más comer pizza', 'Nunca más comer chocolate'],
    ['Saber todos los idiomas', 'Tocar todos los instrumentos'],
    ['Una cita sorpresa', 'Una cita planeada al detalle'],
    ['Viajar al pasado', 'Viajar al futuro'],
    ['Cantar en público', 'Bailar en público'],
    ['Un año sin redes sociales', 'Un año sin series'],
    ['Despertar con desayuno en la cama', 'Despertar con un masaje'],
    ['Una casa enorme en el campo', 'Un departamento pequeño en el centro'],
    ['Ser famoso', 'Ser millonario en secreto'],
    ['Leer la mente', 'Ver el futuro'],
    ['Hacer un viaje en auto', 'Hacer un crucero'],
    ['Tener un dragón', 'Ser un dragón'],
    ['Comer solo comida dulce', 'Comer solo comida salada'],
    ['Que te escriban una carta', 'Que te canten una canción'],
    ['Acampar bajo las estrellas', 'Dormir en un hotel de lujo'],
    ['Hablar con los animales', 'Hablar con las plantas'],
    ['Siempre tener frío', 'Siempre tener calor'],
    ['Un beso largo', 'Muchos besos cortos'],
    ['Bailar lento en la cocina', 'Bailar en una fiesta llena de gente'],
    ['Perder el celular', 'Perder las llaves'],
    ['Vivir sin música', 'Vivir sin películas'],
    ['Cenar a la luz de las velas', 'Cenar en el piso con picnic'],
    ['Saber cocinar perfecto', 'Saber dibujar perfecto'],
    ['Que nos vean besándonos', 'Que lean nuestros mensajes'],
    ['Un viaje a Japón', 'Un viaje a Italia'],
    ['Reír hasta llorar', 'Llorar de emoción'],
    ['Teletransportarte', 'Detener el tiempo'],
    ['Ser siempre puntual', 'Que siempre te esperen'],
    ['Lluvia en la ventana y manta', 'Sol y hamaca'],
    ['Que te miren a los ojos', 'Que te tomen de la mano'],
    ['Repetir nuestra primera cita', 'Inventar una totalmente nueva'],
    ['Un perro gigante', 'Diez gatos pequeños'],
    ['Mensajes de voz', 'Mensajes de texto']
  ],

  // ───────────────── ¿CUÁNTO ME CONOCES? ─────────────────
  conoces: [
    '¿Cuál es mi comida favorita para un día triste?',
    '¿Qué me da más miedo?',
    '¿Cuál es la canción que más he escuchado este año?',
    '¿Qué haría con un día libre sin planes?',
    '¿Cuál es mi película favorita de la infancia?',
    '¿Qué es lo que más me molesta que hagan en la mesa?',
    '¿Qué superpoder elegiría?',
    '¿A qué país viajaría mañana mismo?',
    '¿Cuál es mi bebida favorita?',
    '¿Qué es lo primero que hago al despertar?',
    '¿Qué trabajo tendría si no hiciera lo que hago?',
    '¿Cuál es mi mayor manía?',
    '¿Qué regalo me haría más ilusión?',
    '¿Qué olor me encanta?',
    '¿Cuál fue mi primer trabajo?',
    '¿Qué serie volvería a ver desde el principio?',
    '¿Cuál es mi postre favorito?',
    '¿Qué palabra uso demasiado?',
    '¿Cuál es mi mayor placer culposo?',
    '¿Qué animal sería?',
    '¿Qué me hace reír sin falta?',
    '¿Qué hago cuando estoy nervioso o nerviosa?',
    '¿Cuál es mi estación del año favorita?',
    '¿Qué es lo que más extraño de mi infancia?',
    '¿Qué me pediría en un restaurante que no conozco?',
    '¿Cuál es mi recuerdo favorito contigo?',
    '¿Con qué personaje de ficción me identifico?',
    '¿Qué cosa nunca comería?',
    '¿Qué es lo que más valoro en una amistad?',
    '¿Qué me pondría para una noche perfecta en casa?'
  ],


  // ───────────────── ENTRE SÁBANAS (adivina mi respuesta, versión picante) ─────────────────
  sabanas: [
    '¿Cuál es mi posición favorita?',
    '¿Qué es lo que más extraño de ti cuando no estamos juntos?',
    '¿Dónde me gusta más que me besen?',
    '¿Qué prenda tuya me vuelve loco o loca?',
    '¿En qué momento del día tengo más ganas?',
    '¿Luz encendida o apagada?',
    '¿Qué parte de tu cuerpo es mi favorita?',
    '¿Cuál fue nuestra mejor noche juntos?',
    '¿Qué me gustaría probar contigo que todavía no hicimos?',
    '¿Lento y romántico o con ganas y sin pausa?',
    '¿Qué es lo primero que voy a hacer cuando te vea?',
    '¿Cuál es el lugar más atrevido donde lo hicimos?',
    '¿Qué frase tuya me enciende?',
    '¿Mañana, tarde o noche?',
    '¿Qué ropa interior me gusta que uses?',
    '¿Qué me pone más: que me mires, que me hables al oído o que me toques?',
    '¿Qué recuerdo nuestro en la cama repito en mi cabeza?',
    '¿Ducha juntos: sí o no?',
    '¿Qué es lo que más me gusta que me hagas?',
    '¿Prefiero tomar la iniciativa o que la tomes tú?',
    '¿Qué canción pondría de fondo?',
    '¿Qué parte de tu cuerpo besaría primero al verte?',
    '¿Qué me gustaría que me mandaras esta noche?',
    '¿Despertar juntos con mimos o con algo más?',
    '¿Qué es lo que más extraño de nuestras noches?',
    'Del 1 al 10, ¿qué tan débil soy si me besas el cuello?',
    '¿Cuál es mi juego previo favorito?',
    '¿Qué fantasía tengo que todavía no me animo a contarte?',
    '¿Cuánto aguanto sin pensar en ti de esa forma?',
    '¿Qué me pondría para recibirte en el aeropuerto?'
  ],
  // ───────────────── EN LA MISMA ONDA ─────────────────
  onda: [
    { q: '¿Qué tan buen plan es acampar?', l: 'Pésimo', r: 'Maravilloso' },
    { q: '¿Qué tan picante aguantas la comida?', l: 'Nada', r: 'Fuego puro' },
    { q: '¿Qué tan romántica es una cena en el auto?', l: 'Nada', r: 'Lo más' },
    { q: '¿Qué tan aceptable es la piña en la pizza?', l: 'Delito', r: 'Obra maestra' },
    { q: '¿Qué tan importante es hacer la cama?', l: 'Irrelevante', r: 'Sagrado' },
    { q: '¿Qué tan buena idea es un tatuaje de pareja?', l: 'Terrible', r: 'Genial' },
    { q: '¿Qué tan aterrador es hablar en público?', l: 'Nada', r: 'Pánico' },
    { q: '¿Qué tan bueno es el reguetón?', l: 'Horrible', r: 'Arte' },
    { q: '¿Qué tan aceptable es responder mensajes horas después?', l: 'Imperdonable', r: 'Normalísimo' },
    { q: '¿Qué tan divertido es ir a un museo?', l: 'Aburrido', r: 'Fascinante' },
    { q: '¿Qué tan raro es comer cereal de cena?', l: 'Normal', r: 'Rarísimo' },
    { q: '¿Qué tan importante es la puntualidad?', l: 'Da igual', r: 'Vital' },
    { q: '¿Qué tan cursi es decirse apodos en público?', l: 'Tierno', r: 'Insoportable' },
    { q: '¿Qué tan buena es la mayonesa?', l: 'Asquerosa', r: 'Divina' },
    { q: '¿Qué tan probable es que vivamos en otro país juntos?', l: 'Imposible', r: 'Seguro' },
    { q: '¿Qué tan sexy es saber cocinar?', l: 'Nada', r: 'Muchísimo' },
    { q: '¿Qué tan grave es ver un capítulo sin el otro?', l: 'Nada', r: 'Traición' },
    { q: '¿Qué tan buen regalo son las flores?', l: 'Malo', r: 'El mejor' },
    { q: '¿Qué tan bien bailo?', l: 'Desastre', r: 'Profesional' },
    { q: '¿Qué tan romántica es la lluvia?', l: 'Nada', r: 'Muy romántica' },
    { q: '¿Qué tan aceptable es dormir con calcetines?', l: 'Horror', r: 'Perfecto' },
    { q: '¿Qué tan buen plan es un domingo sin salir de la cama?', l: 'Pérdida de tiempo', r: 'Paraíso' },
    { q: '¿Qué tan competitivo o competitiva eres?', l: 'Nada', r: 'Peligrosamente' },
    { q: '¿Qué tan importante es el primer beso para saber si funciona?', l: 'Nada', r: 'Decisivo' },
    { q: '¿Qué tan bueno sería tener una casa con muchos animales?', l: 'Pesadilla', r: 'Sueño' },
    { q: '¿Qué tan atractiva es una voz grave?', l: 'Nada', r: 'Irresistible' },
    { q: '¿Qué tan buena es la comida de avión?', l: 'Incomible', r: 'Deliciosa' },
    { q: '¿Qué tan aceptable es usar el teléfono en una cena?', l: 'Nunca', r: 'Sin problema' },
    { q: '¿Qué tan divertido es un karaoke?', l: 'Tortura', r: 'Lo mejor' },
    { q: '¿Qué tan coqueto o coqueta es el otro?', l: 'Nada', r: 'Demasiado' },
    { q: '¿Qué tan bueno es el olor a gasolina?', l: 'Asqueroso', r: 'Delicioso' },
    { q: '¿Qué tan pronto deberíamos volver a vernos?', l: 'Cuando se pueda', r: 'Mañana mismo' }
  ],

  // ───────────────── DOS VERDADES Y UNA MENTIRA ─────────────────
  verdades: [
    'Tu infancia', 'Viajes', 'Comida', 'Primeros trabajos', 'El colegio', 'Tu familia', 'Amistades',
    'Cosas que has roto', 'Mascotas', 'Vergüenzas', 'Habilidades ocultas', 'Fiestas', 'Accidentes tontos',
    'Cosas que te dan miedo', 'Récords personales', 'Encuentros con famosos', 'Regalos', 'Tus vacaciones de verano',
    'Lo que pensaste de mí al principio', 'Cosas que nunca has hecho'
  ],

  // ───────────────── ¿DATO REAL O INVENTADO? ─────────────────
  datoCats: { historia: 'Historia', lengua: 'Lengua', ciencia: 'Ciencia', tierra: 'Tierra', espacio: 'Espacio', animales: 'Animales', cuerpo: 'Cuerpo humano', arte: 'Arte' },
  datos: [
    { c: 'animales', t: 'Los pulpos tienen tres corazones.', real: true, e: 'Dos bombean sangre a las branquias y uno al resto del cuerpo.' },
    { c: 'espacio', t: 'Un día en Venus dura más que un año en Venus.', real: true, e: 'Venus tarda unos 243 días terrestres en girar sobre sí mismo y unos 225 en dar la vuelta al Sol.' },
    { c: 'animales', t: 'Los flamencos son rosados por lo que comen.', real: true, e: 'Los pigmentos de las algas y crustáceos que comen tiñen sus plumas.' },
    { c: 'ciencia', t: 'Las bananas son ligeramente radiactivas.', real: true, e: 'Contienen potasio-40, un isótopo natural. Habría que comer cantidades imposibles para que importe.' },
    { c: 'historia', t: 'Cleopatra vivió más cerca de la llegada del hombre a la Luna que de la construcción de la Gran Pirámide.', real: true, e: 'La Gran Pirámide se construyó unos 2500 años antes de Cleopatra; la Luna llegó unos 2000 años después.' },
    { c: 'animales', t: 'Los wombats hacen caca en forma de cubo.', real: true, e: 'La forma se debe a cómo se contrae su intestino. Así marcan territorio sin que ruede.' },
    { c: 'ciencia', t: 'La Torre Eiffel puede crecer unos 15 centímetros en verano.', real: true, e: 'El hierro se dilata con el calor.' },
    { c: 'ciencia', t: 'Un rayo es varias veces más caliente que la superficie del Sol.', real: true, e: 'Un rayo puede alcanzar unos 30.000 °C; la superficie solar ronda los 5.500 °C.' },
    { c: 'animales', t: 'Los tiburones existen desde antes que los árboles.', real: true, e: 'Hay tiburones desde hace unos 400 millones de años; los primeros árboles aparecieron un poco después.' },
    { c: 'ciencia', t: 'Botánicamente, la frutilla no es una baya, pero la banana sí.', real: true, e: 'En botánica, "baya" tiene una definición técnica que la banana cumple y la frutilla no.' },
    { c: 'espacio', t: 'En Marte los atardeceres son azulados.', real: true, e: 'El polvo marciano dispersa la luz de forma distinta que nuestra atmósfera.' },
    { c: 'espacio', t: 'Hay más árboles en la Tierra que estrellas en la Vía Láctea.', real: true, e: 'Se estiman unos 3 billones de árboles frente a unos cientos de miles de millones de estrellas.' },
    { c: 'historia', t: 'La Universidad de Oxford es más antigua que el Imperio azteca.', real: true, e: 'En Oxford ya se enseñaba hacia 1096; Tenochtitlan se fundó en 1325.' },
    { c: 'animales', t: 'Las jirafas tienen la misma cantidad de vértebras en el cuello que los humanos.', real: true, e: 'Siete, solo que muchísimo más largas.' },
    { c: 'animales', t: 'Los koalas tienen huellas dactilares casi idénticas a las humanas.', real: true, e: 'Son tan parecidas que podrían confundir a un experto.' },
    { c: 'historia', t: 'Nintendo empezó en 1889 fabricando naipes.', real: true, e: 'Hacía cartas hanafuda mucho antes de los videojuegos.' },
    { c: 'tierra', t: 'La Antártida es el desierto más grande del mundo.', real: true, e: 'Un desierto se define por la poca lluvia, no por el calor.' },
    { c: 'tierra', t: 'Existen rocas que flotan en el agua.', real: true, e: 'La piedra pómez está llena de burbujas de gas atrapadas al enfriarse la lava.' },
    { c: 'tierra', t: 'El núcleo interno de la Tierra es tan caliente como la superficie del Sol.', real: true, e: 'Ronda los 5.000 a 6.000 °C y aun así es sólido por la enorme presión.' },
    { c: 'tierra', t: 'El Everest crece unos milímetros cada año.', real: true, e: 'La placa india sigue empujando contra la euroasiática.' },
    { c: 'tierra', t: 'Los continentes se mueven más o menos a la velocidad a la que crecen las uñas.', real: true, e: 'Unos pocos centímetros por año.' },
    { c: 'tierra', t: 'Hay mucha más agua dulce bajo tierra que en todos los ríos y lagos juntos.', real: true, e: 'El agua subterránea es cerca de un tercio del agua dulce del planeta; ríos y lagos, menos del 1 %.' },
    { c: 'tierra', t: 'Hay rocas en la Tierra con más de 4.000 millones de años.', real: true, e: 'El gneis de Acasta, en Canadá, ronda los 4.000 millones de años.' },
    { c: 'tierra', t: 'El diamante y la mina de un lápiz están hechos del mismo elemento.', real: true, e: 'Los dos son carbono puro; cambia cómo se ordenan los átomos.' },
    { c: 'tierra', t: 'Todas las playas de Hawái son de arena blanca.', real: false, e: 'Hay playas de arena negra volcánica y hasta una de arena verde por el olivino.' },
    { c: 'tierra', t: 'Los volcanes solo existen en la Tierra.', real: false, e: 'El Monte Olimpo de Marte es un volcán, y la luna Ío de Júpiter tiene cientos activos.' },
    { c: 'espacio', t: 'El Monte Olimpo de Marte es unas dos veces y media más alto que el Everest.', real: true, e: 'Mide unos 22 km de altura frente a los casi 9 km del Everest.' },
    { c: 'espacio', t: 'Una cucharadita de estrella de neutrones pesaría millones de toneladas.', real: true, e: 'Es materia tan comprimida que sus núcleos atómicos están pegados entre sí.' },
    { c: 'ciencia', t: 'En el vacío, una pluma y un martillo caen a la misma velocidad.', real: true, e: 'Lo comprobó un astronauta del Apolo 15 en la Luna, en 1971.' },
    { c: 'espacio', t: 'La luz del Sol que ves ahora salió de él hace unos 8 minutos.', real: true, e: 'Es lo que tarda la luz en recorrer unos 150 millones de kilómetros.' },
    { c: 'ciencia', t: 'El sonido viaja más rápido en el agua que en el aire.', real: true, e: 'Unas cuatro veces más rápido, porque el agua es más densa y menos compresible.' },
    { c: 'espacio', t: 'Los astronautas flotan en la Estación Espacial porque allí no hay gravedad.', real: false, e: 'Allí la gravedad es casi el 90 % de la de la superficie. Flotan porque están en caída libre constante.' },
    { c: 'ciencia', t: 'El agua siempre hierve a 100 °C.', real: false, e: 'Depende de la presión: en la cima de una montaña hierve a menos temperatura.' },
    { c: 'espacio', t: 'Hay estaciones del año porque la Tierra se acerca y se aleja del Sol.', real: false, e: 'Se deben a la inclinación del eje terrestre. De hecho, estamos más cerca del Sol en enero.' },
    { c: 'ciencia', t: 'Con un gramo de oro se puede hacer un hilo de más de dos kilómetros.', real: true, e: 'El oro es el metal más dúctil y maleable que existe.' },
    { c: 'espacio', t: 'El helio se descubrió primero en el Sol que en la Tierra.', real: true, e: 'Se detectó en 1868 en el espectro solar; de ahí su nombre, de Helios.' },
    { c: 'ciencia', t: 'El hielo flota porque el agua se expande al congelarse.', real: true, e: 'Al congelarse ocupa cerca de un 9 % más de volumen y queda menos densa.' },
    { c: 'cuerpo', t: 'La sangre es azul dentro del cuerpo y se vuelve roja al tocar el aire.', real: false, e: 'Siempre es roja; las venas se ven azules por cómo la piel filtra la luz.' },
    { c: 'animales', t: 'En los caballitos de mar, el macho es el que lleva el embarazo.', real: true, e: 'La hembra deposita los huevos en una bolsa del macho, que da a luz a las crías.' },
    { c: 'animales', t: 'Las cebras tienen la piel blanca con rayas negras.', real: false, e: 'Su piel es oscura; las rayas blancas son pelo sin pigmento.' },
    { c: 'historia', t: 'Los vikingos usaban cascos con cuernos.', real: false, e: 'No hay evidencia. La imagen viene de vestuarios de ópera del siglo XIX.' },
    { c: 'historia', t: 'En la Edad Media se creía que la Tierra era plana.', real: false, e: 'La gente educada sabía que era redonda desde la Grecia antigua.' },
    { c: 'espacio', t: 'Cerca del centro de nuestra galaxia hay una nube gigante de alcohol.', real: true, e: 'La nube Sagitario B2 contiene etanol, entre otras moléculas. Prost.' },
    { c: 'espacio', t: 'Un año en Plutón dura unos 248 años terrestres.', real: true, e: 'Desde que se descubrió en 1930 todavía no completó una vuelta al Sol.' },
    { c: 'espacio', t: 'La Luna se aleja de la Tierra unos 4 centímetros por año.', real: true, e: 'Se mide con láseres que rebotan en espejos que dejaron las misiones Apolo.' },
    { c: 'animales', t: 'Las abejas pueden reconocer rostros humanos.', real: true, e: 'En experimentos aprendieron a distinguir fotos de caras, como si fueran flores.' },
    { c: 'animales', t: 'Los delfines duermen con los dos ojos cerrados flotando boca arriba.', real: false, e: 'Duermen con medio cerebro a la vez y suelen dejar un ojo abierto.' },
    { c: 'historia', t: 'La Gran Muralla China se ve a simple vista desde la Luna.', real: false, e: 'Es larga pero muy angosta; desde la Luna no se distingue.' },
    { c: 'animales', t: 'Los camellos guardan agua en sus jorobas.', real: false, e: 'Las jorobas guardan grasa, no agua.' },
    { c: 'animales', t: 'Los peces dorados tienen memoria de solo tres segundos.', real: false, e: 'Pueden recordar cosas durante meses.' },
    { c: 'animales', t: 'Los murciélagos son ciegos.', real: false, e: 'Ven perfectamente; además usan la ecolocalización.' },
    { c: 'animales', t: 'Los avestruces esconden la cabeza en la tierra cuando tienen miedo.', real: false, e: 'Se agachan o huyen corriendo, y muy rápido.' },
    { c: 'cuerpo', t: 'Solo usamos el 10 % de nuestro cerebro.', real: false, e: 'Usamos prácticamente todo el cerebro, aunque no todo al mismo tiempo.' },
    { c: 'ciencia', t: 'Un rayo nunca cae dos veces en el mismo lugar.', real: false, e: 'Los edificios altos reciben rayos muchas veces al año.' },
    { c: 'espacio', t: 'Mercurio es el planeta más caliente del sistema solar.', real: false, e: 'Es Venus, por su atmósfera densa que atrapa el calor.' },
    { c: 'animales', t: 'Los toros se enfurecen al ver el color rojo.', real: false, e: 'Reaccionan al movimiento de la capa, no al color.' },
    { c: 'tierra', t: 'El Everest es la montaña más alta medida desde su base.', real: false, e: 'Medido desde su base en el fondo del mar, el Mauna Kea de Hawái es más alto.' },
    { c: 'tierra', t: 'Las arenas movedizas pueden tragarse a una persona entera.', real: false, e: 'El cuerpo humano flota en ellas; uno se hunde como mucho hasta la cintura.' },
    { c: 'historia', t: 'Einstein reprobó matemáticas en el colegio.', real: false, e: 'Era excelente en matemáticas desde muy joven.' },
    { c: 'tierra', t: 'Los diamantes se forman a partir del carbón.', real: false, e: 'Se forman con carbono a gran profundidad en el manto, no a partir de carbón mineral.' },
    { c: 'historia', t: 'Napoleón medía alrededor de 1,50 metros.', real: false, e: 'Medía cerca de 1,69 m, normal para su época. La confusión vino de las unidades francesas.' },
    { c: 'ciencia', t: 'El vidrio es un líquido que fluye muy lentamente.', real: false, e: 'Los vitrales antiguos son desiguales por cómo se fabricaban, no porque el vidrio fluya.' },
    { c: 'lengua', t: 'La palabra «murciélago» tiene las cinco vocales.', real: true, e: 'Y además cada una aparece una sola vez.' },
    { c: 'lengua', t: '«Ojalá» viene del árabe y significa algo como «si Dios quiere».', real: true, e: 'Es una herencia de casi ocho siglos de presencia árabe en la península ibérica.' },
    { c: 'lengua', t: 'La ñ nació de una doble n que los copistas abreviaban con una rayita encima.', real: true, e: 'Para ahorrar pergamino escribían una sola n con una virgulilla: así nació la tilde de la ñ.' },
    { c: 'lengua', t: 'El español es el idioma con más hablantes nativos del mundo.', real: false, e: 'Es el chino mandarín. El español está segundo.' },
    { c: 'lengua', t: '«Esdrújula» es una palabra esdrújula.', real: true, e: 'Es-drú-ju-la: el acento cae en la antepenúltima sílaba.' },
    { c: 'lengua', t: 'En alemán, todos los sustantivos se escriben con mayúscula.', real: true, e: 'No solo los nombres propios: también der Hund, die Liebe o das Bier.' },
    { c: 'lengua', t: 'En alemán existe una palabra para los kilos que subes comiendo por tristeza: «Kummerspeck».', real: true, e: 'Literalmente significa «tocino de pena».' },
    { c: 'lengua', t: '«Almohada» viene del árabe.', real: true, e: 'De al-mujadda, algo así como «donde se apoya la mejilla».' },
    { c: 'lengua', t: '«Usted» viene de «vuestra merced».', real: true, e: 'Con el uso se fue gastando: vuesarced, vusted, usted.' },
    { c: 'lengua', t: 'La palabra «robot» la inventó un escritor checo.', real: true, e: 'Apareció en una obra de Karel Čapek en 1920; la idea fue de su hermano Josef.' },
    { c: 'lengua', t: '«Zanahoria» viene del latín.', real: false, e: 'Viene del árabe andalusí.' },
    { c: 'lengua', t: '«OK» nació como una broma de periodistas: «oll korrect».', real: true, e: 'Una moda de abreviar mal a propósito en diarios de Boston, en 1839.' },
    { c: 'lengua', t: 'La «ch» y la «ll» siguen siendo letras del abecedario español.', real: false, e: 'Desde 2010 la RAE las considera dígrafos, no letras.' },
    { c: 'historia', t: 'La guerra más corta de la historia duró menos de una hora.', real: true, e: 'La guerra anglo-zanzibariana de 1896 duró unos 40 minutos.' },
    { c: 'historia', t: 'Argentina declaró su independencia el 25 de mayo de 1810.', real: false, e: 'El 25 de mayo de 1810 fue la Revolución de Mayo. La independencia se declaró el 9 de julio de 1816.' },
    { c: 'historia', t: 'El acta de independencia de Venezuela, de 1811, fue la primera de Hispanoamérica.', real: true, e: 'Se firmó el 5 de julio de 1811 en Caracas.' },
    { c: 'historia', t: 'Cleopatra pertenecía a una dinastía de origen griego.', real: true, e: 'Era de la dinastía ptolemaica, de origen macedonio. Fue de las pocas de su familia en aprender egipcio.' },
    { c: 'historia', t: 'La Torre Eiffel se construyó para durar solo 20 años.', real: true, e: 'El permiso inicial era de 20 años; la salvó su uso como antena de radio.' },
    { c: 'historia', t: 'En la antigua Roma se usaba orina para lavar la ropa.', real: true, e: 'El amoníaco de la orina ayudaba a quitar manchas. Hasta se cobraba un impuesto por recolectarla.' },
    { c: 'historia', t: 'El Muro de Berlín cayó en 1989.', real: true, e: 'El 9 de noviembre de 1989.' },
    { c: 'arte', t: 'La Mona Lisa no tiene cejas visibles.', real: true, e: 'Puede que se hayan borrado con limpiezas, o que nunca se pintaran con detalle.' },
    { c: 'arte', t: 'Beethoven compuso su Novena Sinfonía cuando ya estaba casi sordo.', real: true, e: 'En el estreno tuvieron que girarlo para que viera los aplausos.' },
    { c: 'arte', t: 'Van Gogh vendió cientos de cuadros en vida.', real: false, e: 'Solo hay registro seguro de muy pocas ventas; la fama llegó después de su muerte.' },
    { c: 'arte', t: 'La Estatua de la Libertad fue un regalo de Francia a Estados Unidos.', real: true, e: 'Se inauguró en 1886. Su estructura interna la diseñó Gustave Eiffel.' },
    { c: 'cuerpo', t: 'El estómago renueva su revestimiento cada pocos días para no digerirse a sí mismo.', real: true, e: 'Las células de la mucosa se reemplazan muy rápido por el ácido.' },
    { c: 'cuerpo', t: 'Los humanos tenemos solo cinco sentidos.', real: false, e: 'También está el equilibrio, la percepción de la posición del cuerpo, la temperatura, el dolor…' },
    { c: 'ciencia', t: 'Si el Sol desapareciera, lo notaríamos recién unos 8 minutos después.', real: true, e: 'Ni la luz ni la gravedad viajan más rápido que la velocidad de la luz.' }
  ],


  // ───────────────── ¿QUÉ ES MÁS? ─────────────────
  mas: [
    { q: '¿Qué es más grande?', a: 'La Luna', b: 'Plutón', ok: 'a', e: 'La Luna mide unos 3.470 km de diámetro; Plutón, unos 2.380.' },
    { q: '¿Quién tiene más huesos?', a: 'Un bebé', b: 'Un adulto', ok: 'a', e: 'Un bebé nace con unos 300; muchos se fusionan hasta quedar 206.' },
    { q: '¿Qué es más antiguo?', a: 'Stonehenge', b: 'La Gran Pirámide', ok: 'a', e: 'Las primeras fases de Stonehenge son de hacia el 3000 a. C.; la pirámide de Guiza, de hacia el 2560 a. C.' },
    { q: '¿Qué planeta es más caliente?', a: 'Mercurio', b: 'Venus', ok: 'b', e: 'Venus, por su efecto invernadero brutal, aunque está más lejos del Sol.' },
    { q: '¿Qué día dura más?', a: 'Un día en la Tierra', b: 'Un día en Marte', ok: 'b', e: 'Un día marciano dura unas 24 horas y 37 minutos.' },
    { q: '¿Qué país tiene más habitantes?', a: 'Argentina', b: 'Alemania', ok: 'b', e: 'Alemania tiene unos 84 millones; Argentina, unos 46.' },
    { q: '¿Qué es más profundo o más alto?', a: 'La fosa de las Marianas', b: 'El Everest', ok: 'a', e: 'La fosa baja casi 11.000 m; el Everest sube unos 8.850.' },
    { q: '¿Qué es más grande?', a: 'Groenlandia', b: 'Argentina', ok: 'b', e: 'Argentina tiene unos 2,8 millones de km²; Groenlandia, unos 2,2. Los mapas engañan.' },
    { q: '¿Qué es más grande?', a: 'África', b: 'Rusia', ok: 'a', e: 'África tiene más de 30 millones de km²; Rusia, unos 17.' },
    { q: '¿Qué es más denso?', a: 'El oro', b: 'El plomo', ok: 'a', e: 'El oro pesa unos 19,3 g por cm³; el plomo, unos 11,3.' },
    { q: '¿Qué tiene más agua, en proporción?', a: 'Una persona', b: 'Un pepino', ok: 'b', e: 'El pepino es cerca de 95 % agua; una persona adulta, alrededor del 60 %.' },
    { q: '¿Qué universidad es más antigua?', a: 'La de Córdoba', b: 'Harvard', ok: 'a', e: 'La Universidad de Córdoba se fundó en 1613; Harvard, en 1636.' },
    { q: '¿Qué cordillera es más larga?', a: 'Los Andes', b: 'El Himalaya', ok: 'a', e: 'Los Andes tienen unos 7.000 km; el Himalaya, unos 2.400.' },
    { q: '¿Qué montaña es más alta?', a: 'El Aconcagua', b: 'El Kilimanjaro', ok: 'a', e: 'El Aconcagua mide unos 6.960 m; el Kilimanjaro, unos 5.900.' },
    { q: '¿Qué es más ancho?', a: 'La Luna', b: 'Australia', ok: 'b', e: 'Australia mide unos 4.000 km de ancho; la Luna, unos 3.470 de diámetro.' },
    { q: '¿Qué está más cerca de Córdoba?', a: 'La Estación Espacial, cuando pasa por arriba', b: 'Buenos Aires', ok: 'a', e: 'La Estación orbita a unos 400 km; Buenos Aires está a unos 650 km por ruta.' },
    { q: '¿Quién tiene más cromosomas?', a: 'Un ser humano', b: 'Una papa', ok: 'b', e: 'La papa tiene 48; nosotros, 46.' },
    { q: '¿Qué viaja más rápido?', a: 'La luz en el aire', b: 'La luz en el agua', ok: 'a', e: 'En el agua la luz va cerca de un 25 % más lenta.' },
    { q: '¿Qué es más rápido?', a: 'Un guepardo', b: 'Un caballo de carreras', ok: 'a', e: 'El guepardo supera los 100 km/h en sprints cortos; un caballo ronda los 70.' },
    { q: '¿Qué está más lejos de Córdoba?', a: 'Alemania', b: 'Japón', ok: 'b', e: 'Japón queda a unos 18.000 km; Alemania, a unos 11.500.' }
  ],
  // ───────────────── YO NUNCA NUNCA ─────────────────
  yonunca: {
    1: { name: 'Suave', chili: '🌶️', cards: [
      'Yo nunca nunca he fingido estar enfermo o enferma para no ir a algo.',
      'Yo nunca nunca he stalkeado a un ex en redes.',
      'Yo nunca nunca he llorado con una película animada.',
      'Yo nunca nunca me he quedado dormido o dormida en el transporte y me pasé de parada.',
      'Yo nunca nunca he mentido sobre mi edad.',
      'Yo nunca nunca he cantado en la ducha a todo volumen.',
      'Yo nunca nunca he enviado un mensaje a la persona equivocada.',
      'Yo nunca nunca he comido algo que se cayó al piso.',
      'Yo nunca nunca me he reído en un momento serio.',
      'Yo nunca nunca he regalado algo que me regalaron.'
    ]},
    2: { name: 'Atrevido', chili: '🌶️🌶️', cards: [
      'Yo nunca nunca he besado a alguien en la primera cita.',
      'Yo nunca nunca he escrito un mensaje atrevido y lo he borrado antes de mandarlo.',
      'Yo nunca nunca he pensado en ti en un momento muy inoportuno.',
      'Yo nunca nunca me he puesto algo pensando en lo que dirías.',
      'Yo nunca nunca he guardado una captura de pantalla de una conversación nuestra.',
      'Yo nunca nunca he tenido un sueño contigo que no te conté.',
      'Yo nunca nunca he coqueteado para conseguir algo.',
      'Yo nunca nunca he besado a alguien bajo la lluvia.',
      'Yo nunca nunca he mirado tus fotos viejas a escondidas.',
      'Yo nunca nunca he ensayado frente al espejo lo que te iba a decir.'
    ]},
    3: { name: 'Sin filtro', chili: '🌶️🌶️🌶️', cards: [
      'Yo nunca nunca he tenido una cita que terminó mejor de lo esperado.',
      'Yo nunca nunca he imaginado nuestro reencuentro con todo detalle.',
      'Yo nunca nunca he dicho algo atrevido en voz alta y me he arrepentido.',
      'Yo nunca nunca he besado a alguien en un lugar donde no debía.',
      'Yo nunca nunca he usado ropa interior especial para una ocasión.',
      'Yo nunca nunca he tenido una fantasía que nunca he contado.',
      'Yo nunca nunca he mandado una foto que después quise borrar.',
      'Yo nunca nunca he perdido la noción del tiempo besando a alguien.',
      'Yo nunca nunca he pensado "esta persona es peligrosa para mí" y me ha gustado.',
      'Yo nunca nunca he planeado una noche romántica en secreto.'
    ]}
  },

  // ───────────────── DADO COQUETO ─────────────────
  dado: {
    acciones: ['Susurra algo sobre', 'Describe en detalle', 'Haz un piropo sobre', 'Mira a cámara 10 segundos pensando en', 'Cuenta un recuerdo sobre', 'Inventa un poema de dos versos sobre'],
    temas: ['mi sonrisa', 'mis manos', 'mi voz', 'nuestro primer beso', 'lo que llevo puesto', 'mis ojos']
  },

  // ───────────────── HISTORIA A DOS VOCES ─────────────────
  historia: {
    inicios: [
      'Era la tercera vez esa semana que el ascensor se detenía entre dos pisos, y esta vez no estaba sola.',
      'Nadie en el pueblo sabía de dónde había salido la carta, pero estaba dirigida a nosotros.',
      'El vuelo llevaba cuarenta minutos de retraso cuando alguien se sentó en el asiento equivocado.',
      'La receta de la abuela tenía un ingrediente que nadie había visto nunca.',
      'Esa noche el hotel solo tenía una habitación disponible.',
      'El mapa estaba dibujado en una servilleta y tenía una cruz roja en medio del mar.',
      'Cuando se apagaron las luces del museo, una de las estatuas se movió.',
      'El taxista dijo que conocía un atajo. Fue lo último normal de la noche.',
      'Habíamos ganado un concurso al que nunca nos inscribimos.',
      'La mudanza iba bien hasta que abrimos la caja que decía "no abrir".'
    ],
    palabras: ['pingüino', 'beso', 'volcán', 'secreto', 'pasaporte', 'tormenta', 'chocolate', 'espía', 'abuela', 'tango',
      'mapa', 'luna', 'empanada', 'disfraz', 'tren', 'sirena', 'llave', 'karaoke', 'fantasma', 'vino',
      'cohete', 'gato', 'sombrero', 'tesoro', 'carta', 'faro', 'paraguas', 'almohada', 'dragón', 'telescopio']
  },

  // ───────────────── CUPONES ─────────────────
  cupones: [
    { i: '🎬', t: 'Mi peli favorita', d: 'La vemos juntos en videollamada, sin quejas ni celular.' },
    { i: '🗓️', t: 'Tú planeas la próxima cita', d: 'Quien perdió organiza la próxima cita virtual de principio a fin.' },
    { i: '🍝', t: 'Yo elijo la cena', d: 'En la próxima llamada los dos cenan lo que yo diga.' },
    { i: '🎵', t: 'Una playlist para mí', d: 'Mínimo diez canciones, cada una con su porqué.' },
    { i: '💌', t: 'Carta en audio', d: 'Un mensaje de voz de al menos dos minutos, solo para mí.' },
    { i: '☀️', t: 'Semana de buenos días', d: 'Siete días seguidos de mensaje de buenos días antes de las 10.' },
    { i: '📺', t: 'Maratón de mi serie', d: 'Tres capítulos de lo que yo quiera, en videollamada.' },
    { i: '🎤', t: 'Serenata por cámara', d: 'Me cantas una canción entera, de principio a fin.' },
    { i: '✈️', t: 'Plan de reencuentro', d: 'Quien perdió investiga vuelos y arma una propuesta para vernos.' },
    { i: '🎮', t: 'Yo elijo el próximo juego', d: 'La próxima noche de juegos empieza con lo que yo diga.' },
    { i: '👗', t: 'Código de vestimenta', d: 'En la próxima llamada te vistes como yo te pida.' },
    { i: '🙊', t: 'Un "sí" sin preguntas', d: 'Para una petición razonable, cuando yo quiera.' }
  ]
};
